version: '2'
services:
  mysql-server:
    image: mysql:5.7
    hostname: mysql-server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro


  flaskapi:
    restart: on-failure:100 #To make sure the app restarts if the flask app fails by starting without mysql connection
    depends_on:
      - mysql-server
    build: FlaskAPI
    ports:
      - "5000:80"  
    links:
      - mysql-server
  
  react-ui:
    depends_on:
      - flaskapi
    build: ui
    ports:
      - "3000:3000"
    





