FROM python:latest

WORKDIR .

EXPOSE 5000

COPY requirements.txt .

COPY Resources /Resources

COPY Utils /Utils

RUN pip install -r requirements.txt

COPY RestApp.py .  

COPY RestAppFullFlowTest.py .

CMD ["python", "RestAppFullFlowTest.py"]

CMD ["python", "RestApp.py"]

